import React from "react"
export default React.createContext({
    numAdmin: "",
    isAdmin: false,
    bool: false,
    id: 0,
    nombre: "",
    apellidos: [],
    email: "",
    password: "",
    piso: null,
    rol: 0,
    comunidades: [],
    setNumAdmin : null,
    setIsAdmin: null,
    setBool: null,
    setId: null,
    setNombre: null,
    setApellidos: null,
    setEmail: null,
    setPassword: null,
    setPiso: null,
    setRol: null,
    setComunidades: null,
    mantainSession:null,
    getIdByMail:null
})